sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  NODE_VERSION: latest

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

install:
  - docker-compose up -d node
  - docker-compose run node about
