sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  NODE_VERSION: latest

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker-compose --version

install:
  - docker-compose up -d --build --remove-orphans node
  - docker-compose run -d --user=$(whoami) node /bin/bash -c "npm run --prefix=/home/$(whoami) about"
  - docker-compose ps node
  - docker-compose logs node
