version: '2'

services:
  node:
    image: redelivre/alpine-node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "username=$username"
        - "NODE_VERSION=$NODE_VERSION"
        
      
