FROM mhart/alpine-node:8
ARG username
ARG gid
ARG groupname
ARG dependencies
ARG pwd
RUN apk --update upgrade \
    && apk add $dependencies \
    && addgroup -g $gid $groupname \
    && adduser -G $groupname -D -h /home/$username $username \
    && echo $username:$pwd | chpasswd \ 
    && echo "%$groupname ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

